services:
  ecommerce-app:
    build:
      context: .
      target: deps
    ports:
      - "3000:3000"
    command: npm run dev
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
  ecommerce-prod:
    build:
      context: .
      target: runner
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
